modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "CC0 1.0 Universal"

[[mods]]
modId = "stardust"
version = "${version}"
displayName = "Stardust"
authors = "starmun"
description = '''
Data driven ores
'''
#logoFile = ""

[[dependencies.stardust]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stardust]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"
